### ISSUE TITLE
TODO 2024

### ISSUE THREAD

**Issue by chrisarevir** [chrisarevir/newsroom#6]
## Must dos
- [x] Add starting Logo to ad
- [x] Add fonts to car image in ad
- [x] Put ad into scenes in OBS
- [x] Test Audio from OBS to zoom
- [ ] Dry runs
- [x] news segment titles
- [x] Add airplane effect to Nick's transition
- [x] Normalize audio on all videos

## Possible, nice to haves
- [ ] Test keypad thing
- [ ] bloopers
- [ ] credits / thank you video

**Comment by chrisarevir** [comment]
- [x] tone down intro news video
- [ ] look into splicing shorter transition
- [x] boost brock audio, very quiet
- [x] tone down intro bumper
- [x] slight tone down on tony bumper
